version: 2
executorType: docker

containerInfo:
  - image: python:3.7

stages:
  build:
    workDir: ~/ronkyuu
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash --login
        name: Install pipenv
        command: |
          pip install --user --upgrade pipenv
      - type: shell
        shell: /bin/bash --login
        name: Install Dependencies
        command: make env
      - type: shell
        shell: /bin/bash --login
        name: Test
        command: make ci
