version: 2
executorType: docker

version: 2
jobs:
  build:
    working_directory: ~/ronkyuu
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout # check out source code to working directory
      - run:
          command: |
            make env
      - run:
          command: |
            make info
      - run:
          command: |
            make test
      - run:
          command: |
            make coverage
