version: 2
executorType: docker

jobs:
  build:
    working_directory: ~/ronkyuu
    docker:
      - image: circleci/python:3.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout # check out source code to working directory
      - run:
          command: |
            make info
      - run:
          command: |
            make dev
      - run:
          command: |
            make coverage
